<?php

/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
    $languageStrings = array(
        'Map' => 'نقشه',
        'EXTENTIONNAME' => 'Google',
        'LBL_UPDATES_CRM' => 'بروز رسانی ها در crm',
        'LBL_UPDATES_GOOGLE' => 'بروزرسانی ها در گوگل',
        'LBL_UPDATED' => 'بروز شده',
        'LBL_ADDED' => 'اضافه شده',
        'LBL_DELETED' => 'حذف شده',
        'LBL_SYNCRONIZED' => 'همگام سازی',
        'LBL_NOT_SYNCRONIZED' => 'شما هنوز همگام سازی نشده اید',
        'LBL_SYNC_BUTTON' => 'همین الان همگام سازی کن',
        'LBL_REMOVE_SYNC' => 'لغو همگام سازی',
        'LBL_MORE_VTIGER' => 'رکورد های بیشتری هست که با ویتایگر همکام سازی شود',
        'LBL_MORE_GOOGLE' => 'رکورد های بیشتری هست که با گوگل همگام سازی شود',
        'Contact Name'=>'نام مخاطب',
        'Email'=>'ایمیل',
        'Mobile Phone'=>'تلفن موبایل',
        'Address' => 'آدرس',
        'Event Title'=>'تیتر رویداد',
        'Start Date'=>'تارخ شروع ',
        'Until Date'=>'تا تاریخ',
        'Description'=>'توضیحات',
        'Office Phone' => 'تلفن دفتر',
        'Work Phone' => 'تلفن کاری',
        'Home Phone' => 'تلفن خانه',
        'SYNC_SETTINGS' => 'تنظیمات همگام سازی مخاطبین',
        'LBL_SELECT_GOOGLE_GROUP_TO_SYNC' => 'انتخاب گروه گوگل',
        'LBL_ADD_CUSTOM_FIELD_MAPPING' => 'Add Custom Mapping',
        'LBL_EMAIL' => 'ایمیل',
        'LBL_PHONE' => 'تلفن',
        'LBL_URL' => 'Url',
        'LBL_CUSTOM' => 'شخصی سازی',
        'LBL_SELECT_SYNC_DIRECTION' => 'مسیر همگام سازی را انتخاب کنید',
        'LBL_BI_DIRECTIONAL_SYNC' => 'همگام سازی هر دوحالت',
        'LBL_ONLY_SYNC_FROM_GOOGLE_TO_VTIGER' => 'فقط از گوگل به ویتایگر',
        'LBL_ONLY_SYNC_FROM_VTIGER_TO_GOOGLE' => 'فقط از ویتایگر به گوگل',
        'Job Title' => 'تیتر',
        'Company' => 'شرکت',
        'Birthday' => 'تولد',
        'Phone' => 'تلفن',
        'URL' => 'Url',
        'phone' => 'تلفن',
        'email' => 'ایمیل',
        'url' => 'Url',
        'home' => 'خانه',
        'work' => 'کار',
        'custom' => 'دلخواه',
        'mobile' => 'موبایل',
        'main' => 'اصلی',
        'work_fax' => 'فکس',
        'home_fax' => 'فکس خانه',
        'pager' => 'پیجر',
        'profile' => 'پروفایل',
        'blog' => 'بلاگ',
        'home-page' => 'Homepage',
        'CALENDAR_SYNC_SETTINGS' => 'تنظیمات همگام سازی تقویم',
        'LBL_SELECT_GOOGLE_CALENDAR_TO_SYNC' => 'انتخاب تقویم گوگل',
        'LBL_SAVE_AND_START_SYNC' => 'ذخیره و شروع همگام سازی',
        'LBL_PRIMARY' => 'اصلی',
        'LBL_SYNC_FROM_GOOGLE_TO_VTIGER' => 'همگام سازی از گوگل به ویتایگر',
        'LBL_SYNC_FROM_VTIGER_TO_GOOGLE' => 'همگام سازی از ویتایگر به گوگل',
        'LBL_GOOGLE_CONNECT_MSG' => 'Connect to a Google account to fetch',
        'LBL_SIGN_IN_WITH_GOOGLE' => 'ورودبا گوگل',
        'LBL_GOOGLE_ACCOUNT_DETAILS' => 'جزئیات اکانت گوگل',
        'LBL_GOOGLE_ACCOUNT_SYNCED_WITH' => 'اکانت گوگل همگام سازی شد با',
        'LBL_CHANGE_USER' => 'تعویض کاربر',
        'LBL_SAVE_AND_IMPORT' => 'ذخیره و نصب',
        'LBL_IMPORT_RESULTS_GOOGLE' => 'نتایج نصب گوگل',
		'LBL_REDIRECT_URL' => 'Redirect url',
		'LBL_REDIRECT_URL_MESSAGE' => 'Copy the following redirect url and paste in your google auth project as image shows',
    );
    $jsLanguageStrings = array(
        'LBL_SYNC_BUTTON' => 'الان همگام سازی کن',
        'LBL_SYNCRONIZING' => 'در حال همگام سازی ....',
        'LBL_NOT_SYNCRONIZE' => 'شما هنوز همگام سازی نشده اید'
    );
