<?php
/* +**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * ***********************************************************************************/

$languageStrings = array(
	'LBL_PUBLISHER' => 'ناشر',
	'LBL_LICENSE' => 'مدرک',
	'LBL_PUBLISHED_ON' => 'منتشر شده در',
	'LBL_INSTALL' => 'نصب',
	'LBL_UPGRADE' => 'ارتقا',
	'LBL_VERSION' => 'نسخه',
	'LBL_DECLINE' => 'Decline',
	'LBL_ACCEPT_AND_INSTALL' => 'قبول و نصب',
	'LBL_OK' => 'OK',
	'LBL_EXTENSION_NOT_COMPATABLE' => 'اکستنشن کامل نیست',
	'LBL_INVALID_FILE' => 'فایل نادرست',
	'LBL_NO_LICENSE_PROVIDED' => 'هیچ مدرکی ارائه نشده',
	'LBL_INSTALLATION' => 'نصبکردن',
	'LBL_FAILED' => 'شکست',
	'LBL_SUCCESSFULL' => 'موفق',
	'LBL_INSTALLATION_LOG' => 'لاگ نصب کردن',
	'LBL_UPDATED_MODULE' => ' مودال با مفقیت بروز شد.',
	'LBL_UPDATING_MODULE' => 'درحال بروز کردن مودال',
	'LBL_MARKET_PLACE' => 'فروشگاه',

	//Extension Store translations
	'LBL_VTIGER_EXTENSION_STORE' => 'فروشگاه اکستنشن ویتایگر',
	'LBL_SEARCH_FOR_AN_EXTENSION' => 'جست و جو برای اکستنشن..',
	'LBL_DOWNLOADS' => 'دانلودها',
	'LBL_NO_EXTENSIONS_FOUND' => 'هیچ اکستنشنی پیدانشد',
	'LBL_REGISTER_TO_MARKET_PLACE' => 'ثبت نام در فروشگاه',
	'LBL_MARKETPLACE_REGISTRATION' => 'ثبت نام در فروشگاه',
	'LBL_MARKETPLACE_LOGIN' => 'لاگین در فروشگاه',
	'LBL_NEW_TO_MARKETPLCAE' => 'جدید هستید در فروشگاه ?',
	'LBL_CREATE_AN_ACCOUNT' => 'ساخت اکانت جدید',
	'LBL_SETUP_CARD_DETAILS' => 'تنظیم جزئیات کارت',
	'LBL_SETUP_CARD' => 'تنظیم کارت',
	'LBL_CARD_NUMBER' => 'شماره کارت',
	'LBL_EXP_MONTH' => 'ماه انقضا',
	'LBL_EXP_YEAR' => 'سال انقضا',
	'LBL_CVC_CODE' => 'کد سی وی سی',
	'LBL_RESET' => 'ریست',
	'LBL_EXTENSION_STORE' => 'فروشگاه اکستنشن',
	'LBL_INSTALLED' => 'نصب شده',
	'LBL_UPDATE_CARD_DETAILS' => 'بروز کرن جزئیات کارت',
	'LBL_BY' => 'توسط',
	'LBL_RATINGS' => 'نمره',
	'LBL_DESCRIPTION' => 'توضیحات',
	'LBL_AUTHOR_INFORMATION' => 'اطلاعات صاحب',
	'LBL_AUTHOR_NAME' => 'نام صاحب',
	'LBL_PHONE' => 'تلفن',
	'LBL_EMAIL' => 'ایمیل',
	'LBL_SCREEN_SHOTS' => 'اسکرین شات ها',
	'LBL_CUSTOMER_RATINGS' => 'نمر مشتری ها',
	'LBL_CUSTOMER_REVIEWS' => 'نقد مشتری ها',
	'LBL_WRITE_A_REVIEW' => 'نقد خود را بنویسید',
	'LBL_CUSTOMER_REVIEW' => 'نقد مشتری',
	'LBL_REVIEW' => 'نقد',
	'LBL_CUSTOMERS_REVIEWED' => 'مشتری ها نقد کردند',
	'LBL_SINGLE_CUSTOMER_REVIEWED' => 'یک مشتری نقد کرد',
	'LBL_INSTALLATION_FAILED' => 'نصب با شکست موتجه شد',
	'LBL_SUCCESSFULL_INSTALLATION' => 'نصب موفق',
	'LBL_INSTALL_FROM_ZIP' => 'نصب از فایل زیپ',
	'LBL_MORE_DETAILS' => 'جزئیات بیشتر',
	'Install' => 'نصب',
	'Upgrade' => 'بروزرسانی',
	'LBL_RATE_IT' => 'نمره دهید.',
	'LBL_UNINSTALL' => 'خذف',
	'LBL_LAUNCH' => 'اجرا',
	'LBL_SIGN_UP_FOR_FREE' => 'ثبت نام رایگان',
	'LBL_EMAIL_ADDRESS' => 'آدرس ایمیل',
	'LBL_FIRST_NAME' => 'اسم کوچک',
	'LBL_LAST_NAME' => 'نام فامیل',
	'LBL_COMPANY_NAME' => 'نام شرکت',
	'LBL_PASSWORD' => 'پسورد',
	'LBL_CONFIRM_PASSWORD' => 'تایید پسورد',
	'LBL_REGISTER' => 'ثبت نام',
	'LBL_EXTENSION_STORE_LOGIN' => 'لاگین اکستنشن استور',
	'LBL_REMEMBER_ME' => 'مرا بیاد دشته باش',
	'LBL_TRY_IT' => 'امتحانش کن',
	'LBL_TRIAL_INSTALLED' => 'Trial Installed',
	'LBL_BUY' => 'خرید ',
	'LBL_LOGIN_TO_MARKET_PLACE' => 'لاگیندر فروشگاه',
	'LBL_LOGIN' => 'لاگین',
	'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'لطفا اکستنشن لودر را نصب کنید',
	'LBL_INSTALL_EXTENSION_LOADER' => 'نصب اکستنشن لودر',
	'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'برای ادامه به استفاده اکستنشن استور لطفا نصب کنید ',
	'LBL_DOWNLOAD' => 'دانلود',
	'LBL_COMPATIABLE_EXTENSION' => ' و فعالش کنید بعنوانzend_extension.',
	'LBL_MORE_DETAILS_ON_INSTALLATION' => 'برای اطلاعات بیشتر در نصب کردن ',
	'LBL_READ_HERE' => 'انجا را بخوانید',
	'LBL_REVIEWS' => 'نقد ها',
	'LBL_SIGNUP_FOR_MARKET_PLACE' => 'ثبت نام در فروشگاه',
	'LBL_UNAUTHORIZED' => 'Unauthorized',
	'LBL_EXPIRY_DATE' => 'تاریخ انقضا',
	'LBL_LOGOUT' => 'لاگ اوت',

	'firstname' => 'نام',
	'lastname' => 'نام خانوادگی',
	'email' => 'ایمیل',
	'company' => 'شرکت',
	'Phone' => 'نلفن',
	'Website' => 'وبسایت',
	'LBL_SECURITY_CODE' => 'کد امنیتی',
	'LBL_WHAT_IS_SECURITY_CODE' => 'کد امنیتی چیست؟ ?',
	'LBL_CARD_NUMBER_PLACEHOLDER' => '16رقم عدد رو کارت',
	'LBL_SECURITY_CODE_HELP_CONTENT' => 'The CVV Number(Card Verification Value) on your credit/debit card is a 3 digit number on VISA®, MasterCard® etc.. branded credit/debit cards.',
	'LBL_ENTER_REGISTERED_EMAIL' => 'ایمیل ثبت شده خود را وارد کنید',
	'LBL_RESET_PASSWORD_LINK_EMAILED' => 'لینک ریست پسورد برای شما ایمیل شد!',
	'LBL_FORGOT_PASSWORD' => 'پسوردم را فراموش کردم',
	'LBL_ALREADY_INSTALLED_MODULE_BUILDER' => 'از قبل ساخته شده توسط سازنده مودال',
	'LBL_REVIEW_RESTRICTED' => 'نقد شما با مشکل مواجه شد',
);
$jsLanguageStrings = array(
	'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION' => 'لطفا جزئیات کارت خود را تنظیم کنید تا این اکستنشن برای شما نصب شود',
	'JS_UPDATE_CARD_DETAILS' => 'بروزرسانی جزئیات کارت',
	'JS_ON' => 'روشن',
	'JS_RATINGS' => 'نمره ها',
	'JS_INSTALLED' => 'نصب شده',
	'JS_TRIAL_INSTALLED' => 'Trial Installed',
	'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'لطفا از لینک زیر برای ادامه کار اکستنشن لودر را نصب کنید',
	'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => 'لطفا برای دانلود این اکستنشن در فروشگاه ثبت نام کنید',
	'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => 'لطفا برای دانلود این اکستنشدپن جزئیات کارت خود را تنظیم کنید',
	'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => 'برای حذف این اکستنشن در فروشگاه وارد شوید',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_INSTALL_THIS_EXTENSION' => 'مطمئن هستید می خواهید این اکستنشن را نصب کنید?',
	'JS_CARD_DETAILS_UPDATED' => 'جزئیات کارت بروز شد!',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT_FROM_EXTENSION' => 'مطمئن هستید میخاهید از اکستنشن خارج شوید?',
	'JS_PASSWORDS_MISMATCH' => "پسورد ها یکی نبود!",
	'JS_ARE_YOU_SURE_UNINSTALL' => 'مطمئن هستید می خواهید این اکستنشن را حذف کنید',
	'JS_ARE_YOU_SURE_INSTALL' => 'مطمئن هستید میخواهید این اکستنشن را نصب کنید',
);