<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor' => 'ویراش کننده لایه',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'فیلد و لایه ویرایش کننده',
	'LBL_CREATE_CUSTOM_FIELD' => 'ساخت فیلد شخصی',
	'LBL_DETAILVIEW_LAYOUT' => 'جزئیات نمای لایه',
	'LBL_ARRANGE_RELATED_TABS' => 'ترتیب بندی تب های مرتبط',
	'LBL_ADD_CUSTOM_FIELD' => 'اضافه کردن فیلد شخصی',
	'LBL_ADD_CUSTOM_BLOCK' => 'اضافه کردن بلوک',
	'LBL_SAVE_FIELD_SEQUENCE' => 'ذخیره ترتیب فیلد ها',
	'LBL_BLOCK_NAME' => 'نام بلاک',
	'LBL_ADD_AFTER' => 'اضافه بعد ',
	'LBL_ACTIONS' => 'فعالیت ها',
	'LBL_ALWAYS_SHOW' => 'همیشه نشان بده',
    'LBL_SHOW_INACTIVE_FIELDS' => 'نشان دادن فیلد های غیر فعال',
	'LBL_SHOW_HIDDEN_FIELDS' => 'نمایش فیلد های مخفی',
	'LBL_DELETE_CUSTOM_BLOCK' => 'حذف از بلاک شخصی',
	'LBL_MANDATORY_FIELD' => 'Mandatory Field',
	'LBL_ACTIVE' => 'فعال',
	'LBL_QUICK_CREATE' => 'ساخت سریع',
	'LBL_SUMMARY_FIELD' => 'نمایش خلاصه',
    'LBL_KEY_FIELD_VIEW' => 'نمایش فیلد کلیدی',
	'LBL_MASS_EDIT' => 'ویرایش کلی',
	'LBL_DEFAULT_VALUE' => 'ارزش پیش فرض',
	'LBL_SELECT_FIELD_TYPE' => 'انتخاب نوع فیلد',
	'LBL_LABEL_NAME' => 'نام برچسب',
	'LBL_LENGTH' => 'طول',
	'LBL_DECIMALS' => 'Decimals',
	'LBL_ENTER_PICKLIST_VALUES' => 'وارد کردن لیست انتخاب شده ارزش ها..',
	'LBL_PICKLIST_VALUES' => 'لیست انتخاب شده ارزش ها',
	'LBL_INACTIVE_FIELDS' => 'فیلد های غیر فعال',
	'LBL_REACTIVATE' => 'دوباره فعال کردن',
	'LBL_ARRANGE_RELATED_LIST' => 'ترتیب بندی لیست مربوط',
	'LBL_SELECT_MODULE_TO_ADD' => 'انتخاب مودال برای اضافه کردن',
    'LBL_SELECT_HIDDEN_MODULE' => 'انتخاب مودال مخفی',
	'LBL_NO_RELATED_INFORMATION' => 'بدون اطلاعات',
	'LBL_RELATED_LIST_INFO' => 'Drag and drop the module to reorder the list',
	'LBL_REMOVE_INFO' => 'روی ایکون حذف کبلیک کنید تا ارتباط را برای همیشه از لیست حذف کنید',
	'LBL_ADD_MODULE_INFO' => 'مودال را از مدال های حذف شده انتخاب کنید تا به لیست باز گردد',
    'LBL_MANY_MANY_TEXT' => 'Many-Many relationships are currently available only for %s and %s',
	'LBL_SELECT_MODULE' => 'انتخاب مودال',
	'LBL_DUPLICATES_EXIST' => 'نام بلاک از قبل وجود',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'Non Role Based Picklist',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'Duplicate Field Exists',
	'LBL_WRONG_FIELD_TYPE' => 'نوع فیلد اشتباه',
	'LBL_ROLE_BASED_PICKLIST' => 'Role Based Picklist',
	'LBL_CLICK_HERE_TO_EDIT' => 'برای ویرایش اینجا را کلیک کنید',
    'LBL_EDIT_FIELD' => 'Edit Field properties: %s',

	//Field Types
	'Text'=>'متن',
	'Decimal'=>'Decimal',
	'Integer'=>'Integer',
	'Percent'=>'درصد',
	'Currency'=>'ارز',
	'Date'=>'تاریخ',
	'Email'=>'ایمیل',
	'Phone'=>'تلفن',
	'PickList'=>'لیست انتخاب شده',
	'MultiSelectCombo'=>'Multi-Select Combo Box',
	'URL' => 'URL',
	'Checkbox' => 'Checkbox',
	'TextArea' => 'Text Area',
	'Skype'=>'اسکایپ',
	'Time'=>'ساعت',
	
	//Translation for module
	'Calendar' => 'وظیفه',
	'LBL_FIELD_COULD_NOT_BE_CREATED'=>'Field %s could not be created',
	'SELECT_MODULE' => 'انتخاب مودال',
    
    //Related Lists 
    'LBL_RELATION_SHIPS' => 'ارتباط ها',
    'LBL_ADD_RELATIONSHIP' => 'اضافه کردن ارتباط',
    'LBL_RELATED_MODULE' => 'مودال های مربوط',
    'LBL_ADDING_RELATIONSHIP' => 'اضافه کردن اتباط برای  %s',
    'LBL_SELECTED_RELATED_MODULE' => 'انتخاب مودال های مربوط',
    'LBL_SELECTED_RELATION_TYPE' => 'انتخاب نوع ارتباط',
    'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => 'یک-یک و چند-یک ارتباط های',
    'ONE_MANY_RELATIONSHIP' => 'ارتاط های یک-چند و چند-چند',
    '1-1' => 'بک به یک',
    '1-N' => 'یک به چند',
    'N-1' => 'چند با یک',
    'N-N' => 'چند با چند',
    
	
	//New layout translations
	'LBL_FIELD_TYPES'                   => 'نوع فیلد', 
	'LBL_BASIC_FIELDS'             => 'فیلد های پایه', 
	'LBL_MANDATORY'                => 'Mandatory Field', 
	'LBL_PROPERTIES'               => 'اموال', 
	'LBL_DRAG_UI_TYPE'             => 'Drag and Drop Field here', 
	'LBL_RELATION_FIELDS'          => 'فیلد های مربوط', 
	'LBL_SELECT_BLOCK'             => 'انتخاب بلاک', 
    'LBL_RELATION_ADDED_SUCCESS'   => 'ارتباط با موفقیت اضافه شد',
    
    'FIELD_NAME_IN_PRIMARY_MODULE' => 'فیلد ارتباط در %s',
    'FIELD_NAME_IN_RELATED_MODULE' => 'فیلد ارتباط در %s',
    'TAB_IN_PRIMARY_MODULE'        => 'Table/Tab in %s',
    'TAB_IN_RELATED_MODULE'        => 'Table/Tab in %s',
    
    'LBL_DETAIL_VIEW'              => 'نمایش جزئیات',
    'LBL_EXPANDED'                 => 'Expanded',
    'LBL_COLLAPSED'                => 'Collapsed',
    
    'LBL_FILED_IN_PRIMARY_HELP_TEXT' => 'Reference field of %s module',
    'LBL_TAB_IN_PRIMARY_HELP_TEXT'   => 'Table/Tab of %s module',
    'LBL_FILED_IN_RELATED_HELP_TEXT' => 'Reference field of  %s module',
    'LBL_TAB_IN_RELATED_HELP_TEXT'   => 'Table/Tab of %s module',
    'LBL_NO_RELATION_TYPE'         => 'هیچ ارتباطی از این نوع وجود ندارد',

	'LBL_CREATE_ITEM_CUSTOM_FIELD' => 'Create Line item Custom Field',
	'LBL_MAP_PRODUCT_FIELD' => 'Map to Products field',
	'LBL_MAP_SERVICE_FIELD' => 'Map to Services field',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD' => 'Enable to map Products field',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD' => 'Enable to map Services field',
    
    //Vtiger7 Strings
    'LBL_NO_RELATED_INFO' => 'هیچ ارتباطی وجود ندارد',
    'LBL_ADD_NEW_FIELD_HERE' => 'اضافه کردن فیلد جدید',
    'LBL_SAVE_LAYOUT' => 'ذخیره لایه',
    'LBL_SHOW_FIELD' => 'نمایش فیلد',
    'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => 'فعال یا غیر فعال کردن فیلد اموال',
    'LBL_PROP_MANDATORY' => 'mandatory',
    'LBL_DEFAULT_VALUE_NOT_SET' => 'ارزش پیشفرض تنظیم نشد',
    'LBL_INFO' => 'Info',
    'LBL_PRODUCTFIELDDEFAULTVALUE' => ' (محصولات )',
    'LBL_SERVICEFIELDDEFAULTVALUE' => ' (خدمات)',
    'LBL_SHOW_THIS_FIELD_IN' => 'اینجا کلیک کنید تا فیلد نشان داده شود در %s نما',
    'LBL_MAKE_THIS_FIELD' => 'اینجا کلیک کنید تا این فیلد را %s',
    'LBL_HIDE_THIS_FIELD_IN' => 'Click here to hide this field in %s view',
    'LBL_NOT_MAKE_THIS_FIELD' => 'Click here to make this field non-%s',
    'LBL_TAB_NAME_HELP_TEXT' => 'List of %s shown in %s record',
    'LBL_TAB_NAME_TEXT' => 'Tab name of %s in %s record',
    'LBL_FILED_NAME_HELP_TEXT' => 'A Reference field to %s in %s record will be added',
    'LBL_FIELD_NAME_TEXT' => 'Field name of %s in %s record',
	'LBL_COLLAPSE_BLOCK' => 'Collapse Block',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW' => 'Collapse the block in detail view',
    'LBL_HEADER' => 'Header',
    'LBL_DETAIL_HEADER' => 'Record header',
    'LBL_HEADER_FIELD' => 'Header View',

	'LBL_DUPLICATE_HANDLING' => 'Duplicate Prevention',
	'LBL_DUPLICATE_CHECK' => 'Enable duplicate check',
	'LBL_DUPLICATION_INFO_MESSAGE' => 'Duplicate prevention feature only prevents new duplicate records from getting created by users and external applications. Records created from Import, and from Workflows will not be checked for duplicates.<br><br>Existing duplicate records can be removed using “Find Duplicates” feature from the module page.',
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => 'Select the unique fields on which duplicate records are to be checked',
	'LBL_SELECT_FIELDS' => 'Select Fields',
	'LBL_MAX_3_FIELDS' => 'Max 3 Fields',
	'LBL_SELECT_RULE' => 'Select rule for handling duplicates',
	'LBL_ALLOW_DUPLICATES' => 'Allow Duplicates',
	'LBL_DO_NOT_ALLOW_DUPLICATES' => 'Do not allow Duplicates',
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => 'Action to take if duplicate record is found while syncing with external application',
	'LBL_PREFER_LATEST_RECORD' => 'Prefer latest record',
	'LBL_PREFER_INTERNAL_RECORD' => 'Prefer internal record',
	'LBL_PREFER_EXTERNAL_RECORD' => 'Prefer external record',
	'LBL_SYNC_TOOLTIP_MESSAGE' => 'Prefer latest record - Most recently modified record data will be retained<br>Prefer internal record - Existing record will be retained as it is<br>Prefer external record - Data from the external application will be copied',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW' => 'Block show enabled',
	'JS_BLOCK_VISIBILITY_HIDE' => 'Block hide enabled',
	'JS_CUSTOM_BLOCK_ADDED' => 'New Custom Block added',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'Blocks Sequence Updated',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'Selected Fields Reactivated',
	'JS_FIELD_DETAILS_SAVED' => 'Field Details Saved',
	'JS_CUSTOM_BLOCK_DELETED' => 'Custom Block Deleted',
	'JS_CUSTOM_FIELD_ADDED' => '%s Field Added',
	'JS_CUSTOM_FIELD_DELETED' => 'Custom Field Deleted',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'Length Should be less than or equal to',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Decimal should be in the range 2 to 5',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Save the changes to update Field sequence',
	'JS_RELATED_INFO_SAVED' => 'Related Info Saved',
	'JS_BLOCK_NAME_EXISTS' => 'Block Name already exists',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'No Inactive Fields',
	'JS_SPECIAL_CHARACTERS' => 'Special Characters like',
	'JS_NOT_ALLOWED' => 'are not allowed',
	'JS_FIELD_SEQUENCE_UPDATED' => 'Field Sequence Updated',
	'JS_DUPLICATES_VALUES_FOUND' => 'Duplicate Values found',
    'JS_FIELD_IN_RELATED_MODULE'  => 'Relation field in %s',
    'JS_TAB_IN_RELATED_MODULE' => 'Table/Tab in %s',
    'JS_FILED_IN_RELATED_HELP_TEXT' => 'Reference field of %s module',
    'JS_TAB_IN_RELATED_HELP_TEXT'   => 'Table/Tab of %s module',
    'JS_TAB_FIELD_DELETION'   => 'Deleting the relationship will delete the %s field in %s module and delete the %s Table/Tab in %s. Do you wish to proceed?',
    'JS_ONE_ONE_RELATION_FIELD_DELETE' => 'This will delete %s field in %s module and will delete %s field in %s module. Do you wish to continue?',
	'JS_CUSTOM_FIELDS_MAX_LIMIT' => 'You can add only maximum of %s custom fields in %s block',
    'JS_DEFAULT_VALUE_NOT_SET' => 'Default value not set',
    'JS_DEFAULT_VALUE' => 'Default Value',
    'JS_SAVE_MODULE_SEQUENCE' => 'Save the changes to update Related Module sequence',
    'JS_PRODUCTFIELDDEFAULTVALUE' => ' (Products)',
    'JS_SERVICEFIELDDEFAULTVALUE' => ' (Services)',
    'JS_TAB_TAB_DELETION' => 'This will delete %s tab in %s module and its data. Do you wish to proceed?',
    'JS_SHOW_THIS_FIELD_IN' => 'Click here to show this field in %s view',
    'JS_MAKE_THIS_FIELD' => 'Click here to make this field %s',
    'JS_HIDE_THIS_FIELD_IN' => 'Click here to hide this field in %s view',
    'JS_NOT_MAKE_THIS_FIELD' => 'Click here to make this field non-%s',
    'JS_TAB_NAME_HELP_TEXT' => 'List of %s shown in %s record',
    'JS_TAB_NAME_TEXT' => 'Tab name of %s in %s record',
    'JS_FILED_NAME_HELP_TEXT' => 'A Reference field to %s in %s record will be added',
    'JS_FIELD_NAME_TEXT' => 'Field name of %s in %s record',
    'JS_PROP_MANDATORY' => 'mandatory',
    'JS_SUMMARY' => 'Summary',
    'JS_KEY_FIELD' => 'Key Field',
    
    'JS_QUICK_CREATE' => 'Quick Create',
    'JS_MASS_EDIT' => 'Mass Edit',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'This operation will result in permanent removal of data.
                                                 When a field is deleted, values stored in this field will be deleted, and cannot be retrieved.
                                                 If you are not sure and want to be able to view this data in the future, you can mark the field as Inactive instead of deleting it. Inactive fields can later be activated at any time.
                                                 Are you sure to delete this field?',
    'JS_FIELD_DELETE_CONFIRMATION' => 'Delete - I dont need the data in this field.',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Status changed Successfully',
    'JS_FIELD_CAN_EITHER_BE_HEADER_OR_SUMMARY_ENABLED' => 'Field can either be an header field or key field',
    'JS_DETAIL_HEADER' => 'Record header',
    'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => 'Maximum %s header fields allowed',
    'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => 'Name fields appear in Header by default',
    'JS_FIELD_IS_HEADER_ENABLED_FOR_VTIGER7' => 'This Field is Header enabled for Vtiger7, It will appear in Summary View',

	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => 'Successfully updated to consider selected fields in duplicates prevention',
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => 'Failed to consider selected fields in duplicates prevention',
	'JS_DUPLICATE_CHECK_DISABLED' => 'Duplicate check is disabled',
);
